spring:
  datasource:
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: scott
      password: 123456
      driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.Oracle1gDialect
        format_sql: true
#配置日志
logging:
  #配置日志文件路径
  level:
    cn.qianshu.tick.controller: info #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\tick.log